#!/usr/bin/python3

def raise_exception_msg(message=""):
    try:
        x = hello
    except NameError:
        print(message)
